services:
  be:
    build: ./Portofolio-BE
    volumes:
      - ./Portofolio-BE/data:/app/data
    env_file:
      - ./Portofolio-BE/.env
    expose:
      - "8888"
    restart: unless-stopped

  fe:
    build:
      context: ./Portofolio-FE
      args:
        BE_URL: http://be:8888
    ports:
      - "8887:8887"
    environment:
      - BE_URL=http://be:8888
    depends_on:
      - be
    restart: unless-stopped
