services:
  fe:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BE_URL=http://be:3000
    depends_on:
      - be
    restart: unless-stopped

  be:
    build: ../Portofolio-BE
    volumes:
      - ../Portofolio-BE/data:/app/data
    env_file:
      - ../Portofolio-BE/.env
    expose:
      - "3000"
    restart: unless-stopped
